version: '2.2'
services:
  nginx:
    build:
      context: .
      dockerfile: deployment/docker/Dockerfile.nginx
      args:
        PHP_FPM_SERVER: php
        PHP_FPM_PORT: 9000
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - php
    links:
      - php
    volumes:
      - .:/var/www/
      - ./deployment/docker/nginx/conf.d:/etc/nginx/conf.d
      - ./deployment/certbot/conf:/etc/letsencrypt
      - ./deployment/certbot/www:/var/www/certbot

  php:
    build:
      context: .
      dockerfile: deployment/docker/Dockerfile
      args:
        XDEBUG: "true"
    volumes:
      - .:/var/www/
      - ./deployment/docker/php.ini:/usr/local/etc/php/conf.d/php.ini
    environment:
      APP_ENV: local
    links:
      - mysql
      - redis

  php-batch:
    build:
      context: .
      dockerfile: deployment/docker/Dockerfile.phpbatch
    volumes:
      - .:/var/www/
    links:
      - mysql
      - redis

  redis:
    image: redis:5.0.6
    ports:
      - ${DOCKER_REDIS_EXTERNAL_PORT-6379}:6379

  mysql:
    #platform: linux/x86_64
    image: mysql:5.7
    volumes:
      - mysqldata:/var/lib/mysql
      - ./deployment/docker/mysql-database-test.sql:/docker-entrypoint-initdb.d/mysql-database-test.sql
    environment:
      MYSQL_DATABASE: app_db
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    ports:
      - ${DOCKER_MYSQL_EXTERNAL_PORT-3306}:3306
    command: [ 'mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci' ]

  phpmyadmin:
    image: phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
    depends_on:
      - mysql

volumes:
  mysqldata:
    driver: local
